---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# pipfun

<!-- badges: start -->

<!-- badges: end -->

The goal of pipfun is to ...

## Installation

You can install the development version of pipfun from
[GitHub](https://github.com/) with:

``` r
# install.packages("remotes")
remotes::install_github("PIP-Technical-Team/pipfun")
```

## Examples

This is a basic example which shows you how to solve a common problem:

```{r example}
library(pipfun)
## basic example code
```

### Saving files

Save a list

```{r save-list}

  tdir <- fs::path_temp("pipfun-l")

  lx <- list(x = 1)
  measure <- "ltst"

  pip_sign_save(x = lx,
              measure = measure,
              msrdir = tdir,
              save_dta = TRUE)
  
  fs::dir_tree(tdir)
  fs::dir_delete(tdir)

```

Save a data-frame

```{r save-dataframe}

  tdir <- fs::path_temp("pipfun-df")

  lx <- data.frame(x = 1)
  measure <- "ltst"

  pip_sign_save(x = lx,
              measure = measure,
              msrdir = tdir,
              save_dta = TRUE)
  
  fs::dir_tree(tdir)
  fs::dir_delete(tdir)
```
